platform :ios, '8.0'

use_frameworks!

target 'TodayNewsSwift' do

    pod 'Kingfisher', '~> 3.9.1'
    pod 'ReactiveCocoa', '~> 5.0.0'
    pod 'Alamofire', '~> 4.4.0'
    pod 'SwiftyJSON'
    
    pod 'HandyJSON', '~> 1.7.1'

end
